### ISSUE TITLE
Restore feature gives an SQL error

### ISSUE THREAD

**Issue by muyncky** [blauwfruit/juice#10]
```
ERROR 1180 (HY000) at line 249: Got error 1 "Operation not permitted" during COMMIT
```

**Comment by zakiblauwfruit** [comment]
### Mariadb v10.5.2 or lower:

<img width="464" alt="image" src="https://github.com/blauwfruit/juice/assets/138442780/531678cb-6532-40ed-ade9-5e5b05d43c5e">

### Mariadb v11 or higher:
Mount database.sql file
```yaml
version: '3'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
      - ./dump:/dump
  
  apache:
    image: prestashop/prestashop:1.7.7.5
    volumes:
      - ./dump:/dump
```
Then:
```zsh
docker-compose exec mysql mariadb-dump -u root -p prestashop > /dump/database.sql
```
